#!/usr/bin/env python3
"""Pangu Nebula Sidecar 哈希清单生成器 (v2.1.0 Phase 0 — P0-W5.1)

构建时调用,生成 sidecar.sha256 清单文件,供 Tauri 启动前完整性校验。

用法:
    python scripts/gen_sidecar_hash.py [--output sidecar.sha256] [--root .]

清单格式 (兼容 sha256sum):
    <sha256>  <relative_path>

校验范围 (critical sidecar files):
    - launch.py
    - server/main.py
    - server/config.py
    - server/api/*.py
    - server/services/*.py (核心服务)
    - server/db/*.py
"""

from __future__ import annotations

import argparse
import hashlib
import sys
from pathlib import Path

# 校验范围: sidecar 关键文件 (Python 业务逻辑)
# 不包含: 测试文件、前端文件、Rust 模块、文档
SIDECAR_PATTERNS = [
    "launch.py",
    "server/main.py",
    "server/config.py",
    "server/__init__.py",
    "server/api/*.py",
    "server/services/__init__.py",
    "server/services/chat_service.py",
    "server/services/memory_service.py",
    "server/services/persona_service.py",
    "server/services/swarm_service.py",
    "server/services/health_check.py",
    "server/services/update_service.py",
    "server/db/__init__.py",
    "server/db/engine.py",
    "server/db/orm.py",
    "pangu_memory_sdk/__init__.py",
    "pangu_memory_sdk/store.py",
    "pangu_memory_sdk/types.py",
]

# 排除模式
EXCLUDE_PATTERNS = [
    "__pycache__",
    "*.pyc",
    ".venv",
    "node_modules",
    "target",
    "dist",
    ".git",
]


def compute_sha256(file_path: Path) -> str:
    """计算文件 SHA-256 哈希 (hex)"""
    hasher = hashlib.sha256()
    with open(file_path, "rb") as f:
        while True:
            chunk = f.read(8192)
            if not chunk:
                break
            hasher.update(chunk)
    return hasher.hexdigest()


def should_exclude(path: Path) -> bool:
    """检查路径是否应排除"""
    parts = path.parts
    for part in parts:
        if part in ("__pycache__", ".venv", "node_modules", "target", "dist", ".git"):
            return True
    return False


def collect_files(root: Path) -> list[Path]:
    """根据 SIDECAR_PATTERNS 收集需要校验的文件"""
    files: set[Path] = set()

    for pattern in SIDECAR_PATTERNS:
        # 使用 glob 匹配
        for matched in root.glob(pattern):
            if matched.is_file() and not should_exclude(matched):
                files.add(matched.resolve())
            elif matched.is_dir():
                # 递归收集目录下所有 .py
                for py_file in matched.rglob("*.py"):
                    if not should_exclude(py_file):
                        files.add(py_file.resolve())

    return sorted(files)


def generate_manifest(root: Path, output: Path) -> int:
    """生成 sidecar.sha256 清单文件

    Returns: 校验的文件数
    """
    root = root.resolve()
    files = collect_files(root)

    if not files:
        print(f"WARNING: No sidecar files found under {root}", file=sys.stderr)
        return 0

    lines: list[str] = []
    lines.append("# Pangu Nebula Sidecar Integrity Manifest")
    lines.append(f"# Generated by scripts/gen_sidecar_hash.py")
    lines.append(f"# Files: {len(files)}")
    lines.append("")

    for file_path in files:
        rel_path = file_path.relative_to(root).as_posix()
        hash_hex = compute_sha256(file_path)
        # sha256sum 兼容格式: <hash>  <path>
        lines.append(f"{hash_hex}  {rel_path}")

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text("\n".join(lines) + "\n", encoding="utf-8")

    print(f"Generated {output} ({len(files)} files)")
    return len(files)


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate sidecar.sha256 integrity manifest"
    )
    parser.add_argument(
        "--output",
        default="sidecar.sha256",
        help="Output manifest file path (default: sidecar.sha256)",
    )
    parser.add_argument(
        "--root",
        default=".",
        help="Project root directory (default: current directory)",
    )
    args = parser.parse_args()

    root = Path(args.root)
    output = Path(args.output)

    if not root.exists():
        print(f"ERROR: Root directory not found: {root}", file=sys.stderr)
        return 1

    count = generate_manifest(root, output)
    print(f"Done: {count} files hashed")
    return 0


if __name__ == "__main__":
    sys.exit(main())
